# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transaction_pb2 as transaction__pb2


class MerchantDetailsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMerchantName = channel.unary_unary(
                '/transaction.MerchantDetails/GetMerchantName',
                request_serializer=transaction__pb2.MerchantId.SerializeToString,
                response_deserializer=transaction__pb2.Merchant.FromString,
                )
        self.GetFullMerchant = channel.unary_unary(
                '/transaction.MerchantDetails/GetFullMerchant',
                request_serializer=transaction__pb2.MerchantId.SerializeToString,
                response_deserializer=transaction__pb2.FullMerchant.FromString,
                )


class MerchantDetailsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMerchantName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFullMerchant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MerchantDetailsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMerchantName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMerchantName,
                    request_deserializer=transaction__pb2.MerchantId.FromString,
                    response_serializer=transaction__pb2.Merchant.SerializeToString,
            ),
            'GetFullMerchant': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFullMerchant,
                    request_deserializer=transaction__pb2.MerchantId.FromString,
                    response_serializer=transaction__pb2.FullMerchant.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction.MerchantDetails', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MerchantDetails(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMerchantName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction.MerchantDetails/GetMerchantName',
            transaction__pb2.MerchantId.SerializeToString,
            transaction__pb2.Merchant.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFullMerchant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction.MerchantDetails/GetFullMerchant',
            transaction__pb2.MerchantId.SerializeToString,
            transaction__pb2.FullMerchant.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
