# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x0btransaction\"\x18\n\nMerchantId\x12\n\n\x02id\x18\x01 \x01(\t\"$\n\x08Merchant\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\xc5\x01\n\x0c\x46ullMerchant\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x03 \x01(\t\x12\x17\n\x0ftransact_amount\x18\x04 \x01(\x02\x12\x13\n\x0b\x63heck_fraud\x18\x05 \x01(\x05\x12\x0b\n\x03\x61ge\x18\x06 \x01(\x05\x12\x0e\n\x06gender\x18\x07 \x01(\t\x12\x13\n\x0bzipcode_ori\x18\x08 \x01(\t\x12\x14\n\x0czipcode_dest\x18\t \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\n \x01(\t2\x9f\x01\n\x0fMerchantDetails\x12\x43\n\x0fGetMerchantName\x12\x17.transaction.MerchantId\x1a\x15.transaction.Merchant\"\x00\x12G\n\x0fGetFullMerchant\x12\x17.transaction.MerchantId\x1a\x19.transaction.FullMerchant\"\x00\x42/\n\x13io.grpc.transactionB\x10TransactionProtoP\x01\xa2\x02\x03TXNb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023io.grpc.transactionB\020TransactionProtoP\001\242\002\003TXN'
  _globals['_MERCHANTID']._serialized_start=34
  _globals['_MERCHANTID']._serialized_end=58
  _globals['_MERCHANT']._serialized_start=60
  _globals['_MERCHANT']._serialized_end=96
  _globals['_FULLMERCHANT']._serialized_start=99
  _globals['_FULLMERCHANT']._serialized_end=296
  _globals['_MERCHANTDETAILS']._serialized_start=299
  _globals['_MERCHANTDETAILS']._serialized_end=458
# @@protoc_insertion_point(module_scope)
